import {extensionDefinitions,sourceMapping,normalizeExtensions} from '../frontend/extensions.js';import {defaultCourses} from '../frontend/course-catalog.js';
import fs from 'node:fs';import vm from 'node:vm';import assert from 'node:assert/strict';import {sections,words,sources} from '../frontend/content.js';import {workbook} from '../frontend/xlsx.js';import {taskDefinitions,taskStates,freshTracking,normalizeTracking,metrics,safeTrainingURL} from '../frontend/tracking-data.js';
const nodes=new Map();const node=selector=>{if(!nodes.has(selector))nodes.set(selector,{innerHTML:'',textContent:'',value:'',dataset:{},addEventListener(){},remove(){},click(){},showModal(){},close(){}});return nodes.get(selector)};
const store=new Map();const ctx=vm.createContext({extensionDefinitions,sourceMapping,normalizeExtensions,defaultCourses,sections,words,sources,workbook,taskDefinitions,taskStates,freshTracking,normalizeTracking,metrics,safeTrainingURL,console,structuredClone,Blob,URL,TextEncoder,setTimeout:()=>{},document:{documentElement:{},querySelector:node,querySelectorAll:()=>[],createElement:()=>node('created'),body:{append(){}}},window:{scrollTo(){},print(){}},localStorage:{getItem:k=>store.get(k),setItem:(k,v)=>store.set(k,v)}});
const source=fs.readFileSync(new URL('../frontend/app.js',import.meta.url),'utf8').replace(/^import .*;$/gm,'');vm.runInContext(source,ctx);const run=s=>vm.runInContext(s,ctx);
for(const lang of ['fr','en'])for(let i=0;i<sections.length;i++){run(`pageView='questionnaire';state.lang='${lang}';state.step=${i};render()`);assert.ok(node('#app').innerHTML.includes(sections[i].title[lang].replaceAll('&','&amp;')));if(sections[i].sample){run(`action('sample')`);assert.ok(!node('#app').innerHTML.includes('[object Object]'))}}
run("state=fresh();state.step=4;action('sample')");assert.equal(run('issues(section()).length'),0);run("d('fields').rows.push(structuredClone(d('fields').rows[0]))");assert.ok(run('issues(section()).length')>0);
run("state=fresh();state.step=4;action('sample');state.step=5;action('sample');sim.form={}");const hidden=run('preview(section())');assert.ok(!hidden.includes('data-form-key="order_number"'));run("sim.form={reason:'Livraison::Retard'}");assert.ok(run('preview(section())').includes('data-form-key="order_number"'));
run("state.step=6;action('sample')");assert.equal(run('issues(section()).length'),0);run("d('views').rows[0].title='a::b::c::d'");assert.ok(run('issues(section()).length')>0);
assert.equal(run("esc('<script>')"),'&lt;script&gt;');assert.ok(run("tree(['__proto__::x','_leaf::y'])").includes('_leaf'));assert.ok(run("safeCSV('=CMD()')").startsWith('"\''));ctx.pasted='a\t"b\nc"\r\nd\te';assert.equal(run('parseDelimited(pasted)[0][1]'),'b\nc');assert.throws(()=>run('validate({schemaVersion:9})'));
run('persist();state=validate(JSON.parse(localStorage.getItem(KEY)))');assert.equal(run('state.schemaVersion'),1);
run("state=fresh();state.step=4;action('sample');download=(name,data)=>{globalThis.exported=JSON.parse(data)};exportAPI()");assert.equal(run('exported.requests[0].body.ticket_field.type'),'tagger');assert.equal(run('exported.requests[0].body.ticket_field.required_in_portal'),true);assert.equal(run('exported.notExecuted'),true);
run("state.step=9;action('sample');sim={group:'Service client',status:'open'};action('testrule')");assert.ok(node('#ruleresult').textContent.includes('Logistique'));run("sim.group='Other';action('testrule')");assert.ok(node('#ruleresult').textContent.includes('Pas de correspondance'));
const blob=workbook([{name:'Fields',rows:[['FR','EN'],['Numéro','Order'],['=1+1','<script>'],['Line\n2','✅']]}]);fs.writeFileSync('/tmp/blueprint-export-test.xlsx',Buffer.from(await blob.arrayBuffer()));
assert.equal(sourceMapping.length,26);assert.equal(run('extensionSheets().length'),12);
console.log('PASS: FR/EN rendering, examples, conditional forms, validation, escaping, CSV safety, paste parsing, roundtrip persistence, API draft, routing, workbook generation.');
